# Generated by Django 4.1.1 on 2022-09-11 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Student Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('no_of_degree', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message="You can't provide negative value.")], verbose_name='How many Degree you have?')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
